-- =============================================================================
-- Supabase schema for Ikigai Masala client configuration
-- Run this in the Supabase SQL Editor (Dashboard > SQL Editor > New query)
-- =============================================================================

-- 1. Menu categories — the slot presets (menu_cat_1 … menu_cat_N)
CREATE TABLE IF NOT EXISTS menu_categories (
    name  TEXT PRIMARY KEY,
    slots TEXT[] NOT NULL
);

-- 2. Clients — each client references a menu category.
-- ``version`` is an optimistic-concurrency counter: GET /client-config
-- returns the current value; PUT must send the same value back and
-- fails with 409 Conflict if another writer bumped it in the meantime.
CREATE TABLE IF NOT EXISTS clients (
    name           TEXT PRIMARY KEY,
    menu_category  TEXT NOT NULL REFERENCES menu_categories(name),
    version        INT  NOT NULL DEFAULT 1,
    created_at     TIMESTAMPTZ DEFAULT now()
);
-- Migration for deployments that created the table before the column
-- existed. No-op on fresh installs since CREATE TABLE above includes it.
ALTER TABLE clients ADD COLUMN IF NOT EXISTS version INT NOT NULL DEFAULT 1;

-- 3. Slot count overrides — e.g. Rippling gets veg_dry x2
CREATE TABLE IF NOT EXISTS slot_count_overrides (
    client_name TEXT NOT NULL REFERENCES clients(name) ON DELETE CASCADE,
    slot        TEXT NOT NULL,
    count       INT  NOT NULL DEFAULT 1 CHECK (count >= 0),
    PRIMARY KEY (client_name, slot)
);

-- 4. Theme overrides — per-client day-to-theme mapping
CREATE TABLE IF NOT EXISTS theme_overrides (
    client_name TEXT NOT NULL REFERENCES clients(name) ON DELETE CASCADE,
    day         TEXT NOT NULL CHECK (day IN ('monday','tuesday','wednesday','thursday','friday')),
    theme       TEXT NOT NULL CHECK (theme IN ('mix','chinese','biryani','south','north')),
    PRIMARY KEY (client_name, day)
);

-- 5. App-level settings (core_min_one_slots, constant_slots, fallback, etc.)
CREATE TABLE IF NOT EXISTS app_settings (
    key   TEXT  PRIMARY KEY,
    value JSONB NOT NULL
);

-- 6. Menu history — per-item history for cooldown tracking
CREATE TABLE IF NOT EXISTS menu_history (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_name   TEXT NOT NULL,
    service_date  DATE NOT NULL,
    slot          TEXT NOT NULL,
    item_base     TEXT NOT NULL
);

-- 7. Week signatures — per-week plan signatures for duplicate detection
CREATE TABLE IF NOT EXISTS week_signatures (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_name     TEXT NOT NULL,
    week_start      DATE NOT NULL,
    week_signature  TEXT NOT NULL,
    created_at      TIMESTAMPTZ DEFAULT now()
);

-- Indexes for fast lookups
CREATE INDEX IF NOT EXISTS idx_slot_overrides_client ON slot_count_overrides(client_name);
CREATE INDEX IF NOT EXISTS idx_theme_overrides_client ON theme_overrides(client_name);
CREATE INDEX IF NOT EXISTS idx_menu_history_client ON menu_history(client_name);
CREATE INDEX IF NOT EXISTS idx_menu_history_date ON menu_history(service_date);
CREATE INDEX IF NOT EXISTS idx_week_signatures_client ON week_signatures(client_name);
CREATE INDEX IF NOT EXISTS idx_week_signatures_week ON week_signatures(week_start);

-- =============================================================================
-- Enable Row Level Security (keep tables accessible via service/anon key)
-- =============================================================================
ALTER TABLE menu_categories     ENABLE ROW LEVEL SECURITY;
ALTER TABLE clients             ENABLE ROW LEVEL SECURITY;
ALTER TABLE slot_count_overrides ENABLE ROW LEVEL SECURITY;
ALTER TABLE theme_overrides     ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_settings        ENABLE ROW LEVEL SECURITY;
ALTER TABLE menu_history        ENABLE ROW LEVEL SECURITY;
ALTER TABLE week_signatures     ENABLE ROW LEVEL SECURITY;

-- Allow full access via the anon key (single-tenant app)
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow all on menu_categories') THEN
    CREATE POLICY "Allow all on menu_categories"     ON menu_categories     FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow all on clients') THEN
    CREATE POLICY "Allow all on clients"             ON clients             FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow all on slot_count_overrides') THEN
    CREATE POLICY "Allow all on slot_count_overrides" ON slot_count_overrides FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow all on theme_overrides') THEN
    CREATE POLICY "Allow all on theme_overrides"     ON theme_overrides     FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow all on app_settings') THEN
    CREATE POLICY "Allow all on app_settings"        ON app_settings        FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow all on menu_history') THEN
    CREATE POLICY "Allow all on menu_history"        ON menu_history        FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow all on week_signatures') THEN
    CREATE POLICY "Allow all on week_signatures"     ON week_signatures     FOR ALL USING (true) WITH CHECK (true);
  END IF;
END
$$;
