"""Every production client configuration, for the all-clients sweep.

A snapshot of the live ``clients`` table — all 43 clients / 57
counters — so ``test_all_clients_generate.py`` proves that *every* client the
tool actually serves still produces a menu, not just a representative subset.
It covers the shapes that ship: multi-counter clients, ``nonveg_main`` counts of
1-3, combo slots, single-theme counters, restricted ``source_pools``,
per-client ``item_cooldown_days`` and ``working_days``, and — since Amadeus
Pune — a client in a city with its own item list and its own ruleset.

Kept as a Python literal rather than a SQL dump so it is reviewable in diffs and
needs no parser. Regenerate it when the live table changes shape; the sweep is
marked ``slow``, so it runs on push-to-main and on demand rather than on every
pull request.

Caveats worth knowing when reading a green run. Everything here is the live
value except:

* ``working_days`` is not in the live table yet, so Quince's three-day week is
  synthetic — kept because it is the only coverage of the horizon filter.
* L&T's ``Non Veg Lunch`` counter serves ``nonveg_main: 1`` live, while the
  client's requirement is the five-dish station (biryani + gravy + dry + kebab +
  egg). The snapshot mirrors live; the test that proves the five-dish behaviour
  raises the count itself, so it does not depend on the live row being changed.
"""

from typing import Any, Dict, List

# Default weekday -> theme map (the app-wide default).
_MIX = {
    'monday': 'mix', 'tuesday': 'chinese', 'wednesday': 'biryani',
    'thursday': 'south', 'friday': 'north',
}

# A counter with no theme_map of its own falls back to the app default.
_NO_THEME_MAP: Dict[str, str] = {}
_THEMES_1 = {
    'monday': 'mix',
    'tuesday': 'biryani',
    'wednesday': 'north',
    'thursday': 'south',
    'friday': 'north',
}
_ALL_SOUTH = {d: 'south' for d in _MIX}
_ALL_NORTH = {d: 'north' for d in _MIX}
_THEMES_2 = {
    'monday': 'mix',
    'tuesday': 'north',
    'wednesday': 'biryani',
    'thursday': 'south',
    'friday': 'north',
}
_THEMES_3 = {
    'monday': 'mix',
    'tuesday': 'mix',
    'wednesday': 'biryani',
    'thursday': 'south',
    'friday': 'north',
}
_THEMES_4 = {
    'monday': 'mix',
    'tuesday': 'chinese',
    'wednesday': 'biryani',
    'thursday': 'mix',
    'friday': 'north',
}
_THEMES_5 = {
    'monday': 'mix',
    'tuesday': 'chinese',
    'wednesday': 'north',
    'thursday': 'mix',
    'friday': 'biryani',
}
_ALL_CHINESE_CONTINENTAL = {d: 'chinese_continental' for d in _MIX}
_ALL_CHINESE = {d: 'chinese' for d in _MIX}
_ALL_BIRYANI = {d: 'biryani' for d in _MIX}


def _c(name, cats, counts=None, themes=None) -> Dict[str, Any]:
    return {
        'name': name,
        'categories': list(cats),
        'slot_counts': dict(counts or {}),
        'theme_map': dict(themes if themes is not None else _MIX),
    }


CLIENTS: List[Dict[str, Any]] = [
    {
        'name': 'Amadeus', 'version': 5, 'city': 'Bangalore',
        'serve_weekends': False, 'item_cooldown_days': 20,
        'source_pools': ['amadeus', 'continental', 'healthineers'],
        'counters': [
            _c('South',
               ['bread', 'rice', 'veg_dry', 'veg_gravy', 'sambar', 'rasam',
                'dessert', 'salad', 'curd', 'papad', 'pickle'],
               {'bread': 1, 'curd': 1, 'dessert': 1, 'rasam': 1, 'rice': 1,
                'salad': 1, 'sambar': 1, 'veg_dry': 1, 'veg_gravy': 1},
               _ALL_SOUTH),
            _c('North',
               ['bread', 'rice', 'veg_dry', 'veg_gravy', 'dal', 'dessert', 'curd',
                'papad', 'pickle'],
               {'bread': 1, 'curd': 1, 'dal': 1, 'dessert': 1, 'rice': 1,
                'veg_dry': 1, 'veg_gravy': 1},
               _ALL_NORTH),
            _c('Chinese',
               ['rice', 'veg_gravy'],
               {'rice': 1, 'veg_gravy': 1},
               _ALL_CHINESE_CONTINENTAL),
        ],
    },
    {
        # The first non-Bangalore client: its city selects the Pune item list
        # (data/raw/city_items/pune.xlsx) and the Pune ruleset. Also the only
        # client with serve_weekends set, so the sweep covers a 7-day horizon.
        # `curd_side` was added in the editor so Sunday's raita is a solved
        # ontology dish rather than a stamped string.
        'name': 'Amadeus Pune', 'version': 1, 'city': 'Pune',
        'serve_weekends': True, 'item_cooldown_days': 20,
        'source_pools': [],
        'counters': [
            _c('Counter 1',
               ['welcome_drink', 'salad', 'bread', 'rice', 'veg_dry', 'veg_gravy',
                'dal', 'dessert', 'white_rice', 'papad', 'curd_side'],
               {'bread': 1, 'curd_side': 1, 'dal': 1, 'dessert': 1, 'rice': 1,
                'salad': 1, 'veg_dry': 1, 'veg_gravy': 1, 'welcome_drink': 1},
               _ALL_NORTH),
        ],
    },
    {
        'name': 'Astrazeneca', 'version': 3, 'city': 'Bangalore',
        'serve_weekends': False, 'item_cooldown_days': 20,
        'source_pools': [],
        'counters': [
            _c('Counter 1',
               ['welcome_drink', 'salad', 'bread', 'rice', 'white_rice', 'veg_dry',
                'veg_gravy', 'rasam', 'dessert', 'curd_side', 'papad',
                'nonveg_main', 'dal_sambar'],
               {'bread': 1, 'curd_side': 1, 'dal_sambar': 1, 'dessert': 1,
                'nonveg_main': 1, 'rasam': 1, 'rice': 1, 'salad': 1, 'veg_dry': 1,
                'veg_gravy': 1, 'welcome_drink': 1},
               {
                   'monday': 'mix',
                   'tuesday': 'mix',
                   'wednesday': 'north',
                   'thursday': 'south',
                   'friday': 'chinese',
               }),
        ],
    },
    {
        'name': 'Ather', 'version': 2, 'city': 'Bangalore',
        'serve_weekends': False, 'item_cooldown_days': 20,
        'source_pools': [],
        'counters': [
            _c('Counter 1',
               ['salad', 'bread', 'rice', 'white_rice', 'veg_dry', 'veg_gravy',
                'dal', 'sambar', 'rasam', 'dessert', 'healthy_rice', 'curd_side',
                'papad'],
               {'bread': 1, 'curd_side': 1, 'dal': 1, 'dessert': 1,
                'healthy_rice': 1, 'rasam': 1, 'rice': 1, 'salad': 1, 'sambar': 1,
                'veg_dry': 1, 'veg_gravy': 1},
               {
                   'monday': 'mix',
                   'tuesday': 'south',
                   'wednesday': 'mix',
                   'thursday': 'south',
                   'friday': 'north',
               }),
        ],
    },
    {
        'name': 'Booking.com', 'version': 3, 'city': 'Bangalore',
        'serve_weekends': False, 'item_cooldown_days': 20,
        'source_pools': [],
        'counters': [
            _c('Counter 1',
               ['welcome_drink', 'soup', 'bread', 'rice', 'veg_dry', 'veg_gravy',
                'starter', 'dal', 'sambar', 'rasam', 'dessert', 'healthy_rice',
                'curd_side', 'nonveg_main'],
               {'bread': 1, 'curd_side': 1, 'dal': 1, 'dessert': 1,
                'healthy_rice': 1, 'nonveg_main': 1, 'rasam': 1, 'rice': 1,
                'sambar': 1, 'soup': 1, 'starter': 2, 'veg_dry': 1, 'veg_gravy': 1,
                'welcome_drink': 1},
               {
                   'monday': 'mix',
                   'tuesday': 'north',
                   'wednesday': 'biryani',
                   'thursday': 'chinese',
                   'friday': 'north',
               }),
        ],
    },
    {
        'name': 'Cargil', 'version': 2, 'city': 'Bangalore',
        'serve_weekends': False, 'item_cooldown_days': None,
        'source_pools': None,
        'counters': [
            _c('Counter 1',
               ['welcome_drink', 'bread', 'rice', 'dal', 'sambar', 'rasam',
                'veg_gravy', 'veg_dry', 'curd_side', 'dessert', 'white_rice',
                'papad', 'pickle'],
               {'bread': 1, 'curd_side': 1, 'dal': 1, 'dessert': 1, 'rasam': 1,
                'rice': 1, 'sambar': 1, 'veg_dry': 1, 'veg_gravy': 1,
                'welcome_drink': 1},
               _MIX),
        ],
    },
    {
        'name': 'Cigna', 'version': 1, 'city': 'Bangalore',
        'serve_weekends': False, 'item_cooldown_days': 20,
        'source_pools': [],
        'counters': [
            _c('Counter 1',
               ['bread', 'rice', 'veg_dry', 'veg_gravy', 'rasam', 'dessert',
                'nonveg_main', 'dal_sambar', 'salad', 'curd', 'papad',
                'white_rice'],
               {'bread': 1, 'curd': 1, 'dal_sambar': 1, 'dessert': 1,
                'nonveg_main': 2, 'rasam': 1, 'rice': 1, 'salad': 1, 'veg_dry': 1,
                'veg_gravy': 1},
               _MIX),
        ],
    },
    {
        'name': 'Citrix', 'version': 2, 'city': 'Bangalore',
        'serve_weekends': False, 'item_cooldown_days': None,
        'source_pools': None,
        'counters': [
            _c('Counter 1',
               ['welcome_drink', 'salad', 'bread', 'rice', 'dal', 'rasam',
                'veg_gravy', 'veg_dry', 'nonveg_main', 'curd_side', 'dessert',
                'white_rice', 'papad', 'pickle'],
               {'bread': 1, 'curd_side': 1, 'dal': 1, 'dessert': 1,
                'nonveg_main': 1, 'rasam': 1, 'rice': 1, 'salad': 1, 'veg_dry': 1,
                'veg_gravy': 1, 'welcome_drink': 1},
               _MIX),
        ],
    },
    {
        'name': 'Clario', 'version': 2, 'city': 'Bangalore',
        'serve_weekends': False, 'item_cooldown_days': None,
        'source_pools': None,
        'counters': [
            _c('Counter 1',
               ['welcome_drink', 'bread', 'rice', 'healthy_rice', 'dal', 'sambar',
                'rasam', 'veg_gravy', 'veg_dry', 'nonveg_main', 'curd_side',
                'dessert', 'white_rice', 'papad', 'pickle'],
               {'bread': 1, 'curd_side': 1, 'dal': 1, 'dessert': 1,
                'healthy_rice': 1, 'nonveg_main': 1, 'rasam': 1, 'rice': 1,
                'sambar': 1, 'veg_dry': 1, 'veg_gravy': 1, 'welcome_drink': 1},
               _MIX),
        ],
    },
    {
        'name': 'Cloudera', 'version': 2, 'city': 'Bangalore',
        'serve_weekends': False, 'item_cooldown_days': 20,
        'source_pools': [],
        'counters': [
            _c('Counter 1',
               ['welcome_drink', 'bread', 'rice', 'white_rice', 'veg_dry',
                'veg_gravy', 'dal', 'dessert', 'healthy_rice', 'curd_side',
                'pickle', 'nonveg_main', 'sambar_rasam'],
               {'bread': 1, 'curd_side': 1, 'dal': 1, 'dessert': 1,
                'healthy_rice': 1, 'nonveg_main': 1, 'rice': 1, 'sambar_rasam': 1,
                'veg_dry': 1, 'veg_gravy': 1, 'welcome_drink': 1},
               _MIX),
        ],
    },
    {
        'name': 'Computa Centre', 'version': 2, 'city': 'Bangalore',
        'serve_weekends': False, 'item_cooldown_days': 20,
        'source_pools': ['computacenter'],
        'counters': [
            _c('Counter 1',
               ['salad', 'bread', 'rice', 'white_rice', 'veg_dry', 'veg_gravy',
                'dal', 'rasam', 'dessert', 'curd_side', 'nonveg_main', 'curd_rice'],
               {'bread': 1, 'curd_rice': 1, 'curd_side': 1, 'dal': 1, 'dessert': 1,
                'nonveg_main': 3, 'rasam': 1, 'rice': 1, 'salad': 1, 'veg_dry': 1,
                'veg_gravy': 1},
               _THEMES_1),
        ],
    },
    {
        'name': 'Continental', 'version': 2, 'city': 'Bangalore',
        'serve_weekends': False, 'item_cooldown_days': 20,
        'source_pools': ['continental', 'healthineers'],
        'counters': [
            _c('South Indian',
               ['salad', 'bread', 'rice', 'white_rice', 'veg_dry', 'veg_gravy',
                'sambar', 'rasam', 'dessert', 'curd_side'],
               {'bread': 1, 'curd_side': 1, 'dessert': 1, 'rasam': 1, 'rice': 1,
                'salad': 1, 'sambar': 1, 'veg_dry': 1, 'veg_gravy': 1},
               _ALL_SOUTH),
            _c('North Indian',
               ['salad', 'bread', 'rice', 'white_rice', 'veg_dry', 'veg_gravy',
                'dal', 'dessert', 'curd_side'],
               {'bread': 1, 'curd_side': 1, 'dal': 1, 'dessert': 1, 'rice': 1,
                'salad': 1, 'veg_dry': 1, 'veg_gravy': 1},
               _MIX),
            _c('Pan Asian',
               ['salad', 'rice', 'veg_gravy', 'starter'],
               {'rice': 1, 'salad': 1, 'starter': 1, 'veg_gravy': 1},
               _ALL_CHINESE),
        ],
    },
    {
        'name': 'Eli Lilly', 'version': 2, 'city': 'Bangalore',
        'serve_weekends': False, 'item_cooldown_days': 20,
        'source_pools': [],
        'counters': [
            _c('Regular Menu',
               ['salad', 'bread', 'rice', 'white_rice', 'veg_dry', 'veg_gravy',
                'dal', 'sambar', 'rasam', 'dessert', 'curd_side', 'nonveg_main'],
               {'bread': 1, 'curd_side': 1, 'dal': 1, 'dessert': 1,
                'nonveg_main': 1, 'rasam': 1, 'rice': 1, 'salad': 1, 'sambar': 1,
                'veg_dry': 1, 'veg_gravy': 1},
               {
                   'monday': 'north',
                   'tuesday': 'south',
                   'wednesday': 'north',
                   'thursday': 'south',
                   'friday': 'biryani',
               }),
        ],
    },
    {
        'name': 'F5', 'version': 2, 'city': 'Bangalore',
        'serve_weekends': False, 'item_cooldown_days': 20,
        'source_pools': [],
        'counters': [
            _c('Counter 1',
               ['welcome_drink', 'salad', 'bread', 'rice', 'white_rice', 'veg_dry',
                'veg_gravy', 'dal', 'sambar', 'rasam', 'dessert', 'curd', 'papad',
                'nonveg_main'],
               {'bread': 1, 'curd': 1, 'dal': 1, 'dessert': 1, 'nonveg_main': 2,
                'rasam': 1, 'rice': 1, 'salad': 1, 'sambar': 1, 'veg_dry': 1,
                'veg_gravy': 1, 'welcome_drink': 1},
               _THEMES_2),
        ],
    },
    {
        'name': 'H&M', 'version': 4, 'city': 'Bangalore',
        'serve_weekends': False, 'item_cooldown_days': 20,
        'source_pools': [],
        'counters': [
            _c('Counter 1',
               ['salad', 'bread', 'rice', 'white_rice', 'veg_dry', 'veg_gravy',
                'dal', 'sambar', 'rasam', 'dessert', 'curd', 'papad',
                'nonveg_main', 'starter'],
               {'bread': 1, 'curd': 1, 'dal': 1, 'dessert': 1, 'nonveg_main': 1,
                'rasam': 1, 'rice': 1, 'salad': 1, 'sambar': 1, 'starter': 1,
                'veg_dry': 1, 'veg_gravy': 1},
               {
                   'monday': 'mix',
                   'tuesday': 'mix',
                   'wednesday': 'biryani',
                   'thursday': 'chinese',
                   'friday': 'north',
               }),
        ],
    },
    {
        'name': 'Icon Blr', 'version': 4, 'city': 'Bangalore',
        'serve_weekends': False, 'item_cooldown_days': 20,
        'source_pools': [],
        'counters': [
            _c('Counter 1',
               ['salad', 'bread', 'rice', 'white_rice', 'veg_dry', 'veg_gravy',
                'dal', 'dessert', 'curd_side', 'papad', 'nonveg_main',
                'sambar_rasam'],
               {'bread': 1, 'curd_side': 1, 'dal': 1, 'dessert': 1,
                'nonveg_main': 2, 'rice': 1, 'salad': 1, 'sambar_rasam': 1,
                'veg_dry': 1, 'veg_gravy': 1},
               _THEMES_3),
        ],
    },
    {
        'name': 'Ikea', 'version': 2, 'city': 'Bangalore',
        'serve_weekends': False, 'item_cooldown_days': 20,
        'source_pools': [],
        'counters': [
            _c('Counter 1',
               ['salad', 'bread', 'rice', 'white_rice', 'veg_dry', 'veg_gravy',
                'dal', 'sambar', 'rasam', 'dessert', 'curd_side', 'papad',
                'pickle', 'nonveg_main'],
               {'bread': 1, 'curd_side': 1, 'dal': 1, 'dessert': 1,
                'nonveg_main': 1, 'rasam': 1, 'rice': 1, 'salad': 1, 'sambar': 1,
                'veg_dry': 1, 'veg_gravy': 1},
               _MIX),
        ],
    },
    {
        'name': 'Infenion', 'version': 3, 'city': 'Bangalore',
        'serve_weekends': False, 'item_cooldown_days': 20,
        'source_pools': [],
        'counters': [
            _c('Counter 1',
               ['salad', 'bread', 'rice', 'white_rice', 'veg_dry', 'veg_gravy',
                'starter', 'dal', 'sambar', 'rasam', 'dessert', 'healthy_rice',
                'curd_side', 'chutney', 'nonveg_main'],
               {'bread': 2, 'curd_side': 1, 'dal': 1, 'dessert': 1,
                'healthy_rice': 1, 'nonveg_main': 1, 'rasam': 1, 'rice': 1,
                'salad': 1, 'sambar': 1, 'starter': 1, 'veg_dry': 1,
                'veg_gravy': 1},
               {
                   'monday': 'mix',
                   'tuesday': 'chinese',
                   'wednesday': 'mix',
                   'thursday': 'mix',
                   'friday': 'biryani',
               }),
        ],
    },
    {
        'name': 'Konsberg', 'version': 2, 'city': 'Bangalore',
        'serve_weekends': False, 'item_cooldown_days': 20,
        'source_pools': [],
        'counters': [
            _c('Counter 1',
               ['salad', 'bread', 'rice', 'white_rice', 'veg_dry', 'veg_gravy',
                'dal', 'sambar', 'rasam', 'dessert', 'curd_side', 'papad',
                'pickle', 'nonveg_main'],
               {'bread': 1, 'curd_side': 1, 'dal': 1, 'dessert': 1,
                'nonveg_main': 1, 'rasam': 1, 'rice': 1, 'salad': 1, 'sambar': 1,
                'veg_dry': 1, 'veg_gravy': 1},
               {
                   'monday': 'mix',
                   'tuesday': 'north',
                   'wednesday': 'mix',
                   'thursday': 'chinese',
                   'friday': 'biryani',
               }),
        ],
    },
    {
        'name': 'L&T', 'version': 3, 'city': 'Bangalore',
        'serve_weekends': False, 'item_cooldown_days': 20,
        'source_pools': [],
        'counters': [
            _c('South Lunch',
               ['salad', 'bread', 'rice', 'white_rice', 'veg_dry', 'veg_gravy',
                'sambar', 'rasam', 'dessert', 'curd_side', 'papad'],
               {'bread': 1, 'curd_side': 1, 'dessert': 1, 'rasam': 1, 'rice': 1,
                'salad': 1, 'sambar': 1, 'veg_dry': 1, 'veg_gravy': 1},
               _ALL_SOUTH),
            _c('North Lunch',
               ['soup', 'salad', 'bread', 'rice', 'white_rice', 'veg_gravy', 'dal',
                'dessert', 'curd_side', 'papad'],
               {'bread': 1, 'curd_side': 1, 'dal': 1, 'dessert': 1, 'rice': 1,
                'salad': 1, 'soup': 1, 'veg_gravy': 1},
               _MIX),
            _c('Non Veg Lunch',
               ['bread', 'curd_side', 'nonveg_main'],
               {'bread': 1, 'curd_side': 1, 'nonveg_main': 1},
               _ALL_BIRYANI),
        ],
    },
    {
        'name': 'Moengage', 'version': 1, 'city': None,
        'serve_weekends': False, 'item_cooldown_days': None,
        'source_pools': None,
        'counters': [
            _c('Counter 1',
               ['bread', 'veg_dry', 'rice', 'veg_gravy', 'dal', 'sambar',
                'nonveg_main', 'rasam', 'white_rice', 'papad', 'pickle',
                'curd_side', 'dessert', 'welcome_drink'],
               {'nonveg_main': 2},
               _NO_THEME_MAP),
        ],
    },
    {
        'name': 'Nike', 'version': 4, 'city': 'Bangalore',
        'serve_weekends': False, 'item_cooldown_days': 20,
        'source_pools': [],
        'counters': [
            _c('Veg Combo',
               ['rice', 'white_rice', 'veg_dry', 'veg_gravy', 'dal', 'dessert',
                'curd', 'bread', 'salad'],
               {'bread': 1, 'curd': 1, 'dal': 1, 'dessert': 1, 'rice': 1,
                'salad': 1, 'veg_dry': 1, 'veg_gravy': 1},
               _THEMES_4),
            _c('Non-Veg Combo',
               ['bread', 'veg_dry', 'dal', 'dessert', 'curd', 'salad', 'rice',
                'white_rice', 'nonveg_main'],
               {'bread': 1, 'curd': 1, 'dal': 1, 'dessert': 1, 'nonveg_main': 1,
                'rice': 1, 'salad': 1, 'veg_dry': 1},
               _THEMES_4),
        ],
    },
    {
        'name': 'Odessia', 'version': 1, 'city': None,
        'serve_weekends': False, 'item_cooldown_days': None,
        'source_pools': None,
        'counters': [
            _c('Counter 1',
               ['bread', 'veg_dry', 'rice', 'veg_gravy', 'nonveg_main', 'dal',
                'rasam', 'white_rice', 'papad', 'pickle', 'curd_side', 'dessert',
                'welcome_drink', 'salad'],
               {},
               _NO_THEME_MAP),
        ],
    },
    {
        'name': 'Piramel Finance', 'version': 3, 'city': 'Bangalore',
        'serve_weekends': False, 'item_cooldown_days': 20,
        'source_pools': [],
        'counters': [
            _c('Counter 1',
               ['welcome_drink', 'salad', 'bread', 'rice', 'white_rice', 'veg_dry',
                'veg_gravy', 'dal', 'rasam', 'dessert', 'curd', 'papad'],
               {'bread': 1, 'curd': 1, 'dal': 1, 'dessert': 1, 'rasam': 1,
                'rice': 1, 'salad': 1, 'veg_dry': 1, 'veg_gravy': 1,
                'welcome_drink': 1},
               {
                   'monday': 'mix',
                   'tuesday': 'north',
                   'wednesday': 'biryani',
                   'thursday': 'chinese',
                   'friday': 'south',
               }),
        ],
    },
    {
        'name': 'Plan View', 'version': 2, 'city': 'Bangalore',
        'serve_weekends': False, 'item_cooldown_days': 20,
        'source_pools': ['infineon'],
        'counters': [
            _c('Counter 1',
               ['welcome_drink', 'salad', 'bread', 'rice', 'white_rice', 'veg_dry',
                'veg_gravy', 'rasam', 'dessert', 'curd', 'dal_sambar',
                'nonveg_main'],
               {'bread': 1, 'curd': 1, 'dal_sambar': 1, 'dessert': 1,
                'nonveg_main': 2, 'rasam': 1, 'rice': 1, 'salad': 1, 'veg_dry': 1,
                'veg_gravy': 1, 'welcome_drink': 1},
               _THEMES_3),
        ],
    },
    {
        'name': 'Plum', 'version': 2, 'city': 'Bangalore',
        'serve_weekends': False, 'item_cooldown_days': 20,
        'source_pools': [],
        'counters': [
            _c('Counter 1',
               ['salad', 'bread', 'rice', 'white_rice', 'veg_dry', 'veg_gravy',
                'starter', 'dal', 'sambar', 'rasam', 'dessert', 'curd', 'papad',
                'nonveg_main'],
               {'bread': 1, 'curd': 1, 'dal': 1, 'dessert': 1, 'nonveg_main': 1,
                'rasam': 1, 'rice': 1, 'salad': 1, 'sambar': 1, 'starter': 1,
                'veg_dry': 1, 'veg_gravy': 1},
               {
                   'monday': 'mix',
                   'tuesday': 'north',
                   'wednesday': 'biryani',
                   'thursday': 'north',
                   'friday': 'north',
               }),
        ],
    },
    {
        'name': 'Quince', 'version': 1, 'city': 'Bangalore',
        'serve_weekends': False, 'item_cooldown_days': 20,
        'source_pools': [],
        'working_days': ['wednesday', 'thursday', 'friday'],
        'counters': [
            _c('Counter 1',
               ['welcome_drink', 'bread', 'rice', 'healthy_rice', 'dal',
                'veg_gravy', 'veg_dry', 'nonveg_main', 'dessert', 'starter',
                'white_rice', 'sambar_rasam', 'curd'],
               {'bread': 1, 'curd': 1, 'dal': 1, 'dessert': 1, 'healthy_rice': 1,
                'nonveg_main': 2, 'rice': 1, 'sambar_rasam': 1, 'starter': 1,
                'veg_dry': 1, 'veg_gravy': 1, 'welcome_drink': 1},
               _THEMES_5),
        ],
    },
    {
        'name': 'Rippling', 'version': 4, 'city': None,
        'serve_weekends': False, 'item_cooldown_days': None,
        'source_pools': None,
        'counters': [
            _c('Counter 1',
               ['welcome_drink', 'soup', 'bread', 'rice', 'dal', 'sambar', 'rasam',
                'veg_gravy', 'veg_dry', 'nonveg_main', 'curd_side', 'dessert',
                'salad'],
               {'veg_dry': 2},
               {
                   'monday': 'biryani',
                   'wednesday': 'mix',
               }),
        ],
    },
    {
        'name': 'Scalar', 'version': 1, 'city': None,
        'serve_weekends': False, 'item_cooldown_days': None,
        'source_pools': None,
        'counters': [
            _c('Counter 1',
               ['bread', 'veg_dry', 'rice', 'veg_gravy', 'nonveg_main', 'dal',
                'sambar', 'starter', 'rasam', 'white_rice', 'papad', 'pickle',
                'curd_side', 'dessert', 'welcome_drink'],
               {},
               _NO_THEME_MAP),
        ],
    },
    {
        'name': 'Siemens Healthineers', 'version': 4, 'city': 'Bangalore',
        'serve_weekends': False, 'item_cooldown_days': 20,
        'source_pools': ['healthineers'],
        'counters': [
            _c('North Indian',
               ['salad', 'bread', 'rice', 'white_rice', 'veg_gravy', 'dal',
                'dessert', 'papad', 'curd'],
               {'bread': 1, 'curd': 1, 'dal': 1, 'dessert': 1, 'rice': 1,
                'salad': 1, 'veg_gravy': 1},
               _ALL_NORTH),
            _c('South Indian',
               ['salad', 'bread', 'rice', 'white_rice', 'veg_gravy', 'sambar',
                'rasam', 'dessert', 'papad', 'veg_dry', 'curd'],
               {'bread': 1, 'curd': 1, 'dessert': 1, 'rasam': 1, 'rice': 1,
                'salad': 1, 'sambar': 1, 'veg_dry': 1, 'veg_gravy': 1},
               _ALL_SOUTH),
            _c('South Indian Non-Veg',
               ['salad', 'rice', 'dessert', 'curd_side', 'nonveg_main'],
               {'curd_side': 1, 'dessert': 1, 'nonveg_main': 1, 'rice': 1,
                'salad': 1},
               {
                   'monday': 'mix',
                   'tuesday': 'mix',
                   'wednesday': 'mix',
                   'thursday': 'biryani',
                   'friday': 'mix',
               }),
        ],
    },
    {
        'name': 'Siemens Technology', 'version': 4, 'city': 'Bangalore',
        'serve_weekends': False, 'item_cooldown_days': 20,
        'source_pools': [],
        'counters': [
            _c('North Veg Lunch',
               ['salad', 'bread', 'rice', 'white_rice', 'veg_dry', 'veg_gravy',
                'dal', 'dessert', 'curd', 'papad'],
               {'bread': 1, 'curd': 1, 'dal': 1, 'dessert': 1, 'rice': 1,
                'salad': 1, 'veg_dry': 1, 'veg_gravy': 1},
               {
                   'monday': 'north',
                   'tuesday': 'north',
                   'wednesday': 'biryani',
                   'thursday': 'chinese',
                   'friday': 'north',
               }),
            _c('South Veg Lunch',
               ['salad', 'bread', 'rice', 'white_rice', 'veg_dry', 'veg_gravy',
                'sambar', 'rasam', 'dessert', 'curd', 'papad'],
               {'bread': 1, 'curd': 1, 'dessert': 1, 'rasam': 1, 'rice': 1,
                'salad': 1, 'sambar': 1, 'veg_dry': 1, 'veg_gravy': 1},
               _MIX),
            _c('Non Veg Lunch',
               ['salad', 'bread', 'dessert', 'curd_side', 'nonveg_main',
                'white_rice', 'dal_sambar'],
               {'bread': 1, 'curd_side': 1, 'dal_sambar': 1, 'dessert': 1,
                'nonveg_main': 3, 'salad': 1},
               {
                   'monday': 'mix',
                   'tuesday': 'north',
                   'wednesday': 'biryani',
                   'thursday': 'mix',
                   'friday': 'biryani',
               }),
        ],
    },
    {
        'name': 'Sinch', 'version': 1, 'city': 'Bangalore',
        'serve_weekends': False, 'item_cooldown_days': 20,
        'source_pools': [],
        'counters': [
            _c('Counter 1',
               ['salad', 'bread', 'rice', 'rasam', 'veg_gravy', 'veg_dry',
                'nonveg_main', 'dessert', 'dal_sambar', 'white_rice', 'curd',
                'papad'],
               {'bread': 1, 'curd': 1, 'dal_sambar': 1, 'dessert': 1,
                'nonveg_main': 1, 'rasam': 1, 'rice': 1, 'salad': 1, 'veg_dry': 1,
                'veg_gravy': 1},
               {
                   'monday': 'mix',
                   'tuesday': 'mix',
                   'wednesday': 'biryani',
                   'thursday': 'mix',
                   'friday': 'north',
               }),
        ],
    },
    {
        'name': 'Stripe', 'version': 1, 'city': None,
        'serve_weekends': False, 'item_cooldown_days': None,
        'source_pools': None,
        'counters': [
            _c('Counter 1',
               ['bread', 'veg_dry', 'rice', 'veg_gravy', 'dal', 'sambar',
                'nonveg_main', 'rasam', 'white_rice', 'papad', 'pickle',
                'curd_side', 'dessert', 'welcome_drink'],
               {'nonveg_main': 2},
               _NO_THEME_MAP),
        ],
    },
    {
        'name': 'Stryker', 'version': 1, 'city': None,
        'serve_weekends': False, 'item_cooldown_days': None,
        'source_pools': None,
        'counters': [
            _c('Counter 1',
               ['bread', 'veg_dry', 'rice', 'veg_gravy', 'nonveg_main', 'dal',
                'sambar', 'rasam', 'white_rice', 'papad', 'pickle', 'curd_side',
                'dessert', 'salad'],
               {},
               _NO_THEME_MAP),
        ],
    },
    {
        'name': 'Take 2', 'version': 2, 'city': 'Bangalore',
        'serve_weekends': False, 'item_cooldown_days': 20,
        'source_pools': [],
        'counters': [
            _c('Counter 1',
               ['welcome_drink', 'soup', 'bread', 'rice', 'white_rice', 'veg_dry',
                'veg_gravy', 'dal', 'sambar', 'rasam', 'dessert', 'curd_side',
                'papad', 'nonveg_main'],
               {'bread': 1, 'curd_side': 1, 'dal': 1, 'dessert': 1,
                'nonveg_main': 2, 'rasam': 1, 'rice': 1, 'sambar': 1, 'soup': 1,
                'veg_dry': 1, 'veg_gravy': 1, 'welcome_drink': 1},
               {
                   'monday': 'mix',
                   'tuesday': 'north',
                   'wednesday': 'biryani',
                   'thursday': 'mix',
                   'friday': 'north',
               }),
        ],
    },
    {
        'name': 'Tekion', 'version': 2, 'city': 'Bangalore',
        'serve_weekends': False, 'item_cooldown_days': 20,
        'source_pools': [],
        'counters': [
            _c('Counter 1',
               ['salad', 'bread', 'rice', 'white_rice', 'veg_dry', 'veg_gravy',
                'dal', 'sambar', 'rasam', 'dessert', 'curd_side', 'papad',
                'pickle', 'nonveg_main'],
               {'bread': 1, 'curd_side': 1, 'dal': 1, 'dessert': 1,
                'nonveg_main': 1, 'rasam': 1, 'rice': 1, 'salad': 1, 'sambar': 1,
                'veg_dry': 1, 'veg_gravy': 1},
               _THEMES_5),
        ],
    },
    {
        'name': 'Telstra', 'version': 2, 'city': 'Bangalore',
        'serve_weekends': False, 'item_cooldown_days': 20,
        'source_pools': [],
        'counters': [
            _c('Counter 1',
               ['salad', 'bread', 'rice', 'white_rice', 'veg_dry', 'veg_gravy',
                'dal', 'sambar', 'rasam', 'dessert', 'curd_side', 'pickle',
                'nonveg_main'],
               {'bread': 1, 'curd_side': 1, 'dal': 1, 'dessert': 1,
                'nonveg_main': 1, 'rasam': 1, 'rice': 1, 'salad': 1, 'sambar': 1,
                'veg_dry': 1, 'veg_gravy': 1},
               _THEMES_2),
        ],
    },
    {
        'name': 'Tessolve', 'version': 2, 'city': 'Bangalore',
        'serve_weekends': False, 'item_cooldown_days': 20,
        'source_pools': [],
        'counters': [
            _c('Counter 1',
               ['welcome_drink', 'bread', 'rice', 'white_rice', 'veg_dry',
                'veg_gravy', 'dal', 'sambar', 'rasam', 'dessert', 'healthy_rice',
                'curd_side', 'papad', 'pickle', 'nonveg_main'],
               {'bread': 1, 'curd_side': 1, 'dal': 1, 'dessert': 1,
                'healthy_rice': 1, 'nonveg_main': 2, 'rasam': 1, 'rice': 1,
                'sambar': 1, 'veg_dry': 1, 'veg_gravy': 1, 'welcome_drink': 1},
               _MIX),
        ],
    },
    {
        'name': 'Thales', 'version': 2, 'city': 'Bangalore',
        'serve_weekends': False, 'item_cooldown_days': 20,
        'source_pools': [],
        'counters': [
            _c('Counter 1',
               ['salad', 'bread', 'rice', 'white_rice', 'veg_dry', 'veg_gravy',
                'dal', 'rasam', 'dessert', 'papad', 'nonveg_main', 'curd'],
               {'bread': 1, 'curd': 1, 'dal': 1, 'dessert': 1, 'nonveg_main': 1,
                'rasam': 1, 'rice': 1, 'salad': 1, 'veg_dry': 1, 'veg_gravy': 1},
               {
                   'monday': 'mix',
                   'tuesday': 'north',
                   'wednesday': 'mix',
                   'thursday': 'mix',
                   'friday': 'biryani',
               }),
        ],
    },
    {
        'name': 'ToastTab', 'version': 2, 'city': 'Bangalore',
        'serve_weekends': False, 'item_cooldown_days': 20,
        'source_pools': [],
        'counters': [
            _c('Counter 1',
               ['salad', 'bread', 'rice', 'white_rice', 'veg_dry', 'veg_gravy',
                'dal', 'rasam', 'dessert', 'curd_side', 'curd_rice', 'pickle',
                'nonveg_main', 'soup', 'welcome_drink'],
               {'bread': 1, 'curd_rice': 1, 'curd_side': 1, 'dal': 1, 'dessert': 1,
                'nonveg_main': 1, 'rasam': 1, 'rice': 1, 'salad': 1, 'soup': 2,
                'veg_dry': 1, 'veg_gravy': 1, 'welcome_drink': 1},
               {
                   'monday': 'north',
                   'tuesday': 'biryani',
                   'wednesday': 'mix',
                   'thursday': 'north',
                   'friday': 'mix',
               }),
        ],
    },
    {
        'name': 'Vector', 'version': 2, 'city': 'Bangalore',
        'serve_weekends': False, 'item_cooldown_days': 20,
        'source_pools': [],
        'counters': [
            _c('Counter 1',
               ['welcome_drink', 'bread', 'rice', 'white_rice', 'veg_dry',
                'veg_gravy', 'dal', 'dessert', 'papad', 'pickle', 'sambar_rasam'],
               {'bread': 1, 'dal': 1, 'dessert': 1, 'rice': 1, 'sambar_rasam': 1,
                'veg_dry': 1, 'veg_gravy': 1, 'welcome_drink': 1},
               {
                   'monday': 'mix',
                   'tuesday': 'mix',
                   'wednesday': 'north',
                   'thursday': 'south',
                   'friday': 'north',
               }),
        ],
    },
    {
        'name': 'Waters', 'version': 1, 'city': 'Bangalore',
        'serve_weekends': False, 'item_cooldown_days': 20,
        'source_pools': [],
        'counters': [
            _c('Roti Veg Combo',
               ['bread', 'veg_dry', 'veg_gravy', 'dal', 'dessert', 'salad',
                'starter'],
               {'bread': 1, 'dal': 1, 'dessert': 1, 'salad': 1, 'starter': 2,
                'veg_dry': 1, 'veg_gravy': 1},
               _THEMES_1),
            _c('Roti Non Veg Combo',
               ['salad', 'bread', 'starter', 'dessert', 'nonveg_main', 'dal'],
               {'bread': 1, 'dal': 1, 'dessert': 1, 'nonveg_main': 2, 'salad': 1,
                'starter': 1},
               _THEMES_1),
            _c('Rice Veg Combo',
               ['salad', 'white_rice', 'veg_gravy', 'veg_dry', 'starter', 'dal',
                'dessert'],
               {'dal': 1, 'dessert': 1, 'salad': 1, 'starter': 2, 'veg_dry': 1,
                'veg_gravy': 1},
               _THEMES_1),
            _c('Non Veg Rice Combo',
               ['salad', 'starter', 'dal', 'dessert', 'nonveg_main', 'white_rice'],
               {'dal': 1, 'dessert': 1, 'nonveg_main': 2, 'salad': 1, 'starter': 1},
               _THEMES_1),
        ],
    },
    {
        'name': 'Zscaler', 'version': 2, 'city': 'Bangalore',
        'serve_weekends': False, 'item_cooldown_days': 20,
        'source_pools': ['zscalar'],
        'counters': [
            _c('Counter 1',
               ['soup', 'salad', 'bread', 'rice', 'white_rice', 'veg_dry',
                'veg_gravy', 'starter', 'dal', 'rasam', 'dessert', 'curd_side',
                'nonveg_main'],
               {'bread': 1, 'curd_side': 1, 'dal': 1, 'dessert': 1,
                'nonveg_main': 1, 'rasam': 1, 'rice': 1, 'salad': 1, 'soup': 1,
                'starter': 1, 'veg_dry': 1, 'veg_gravy': 1},
               {
                   'monday': 'mix',
                   'tuesday': 'biryani',
                   'wednesday': 'mix',
                   'thursday': 'south',
                   'friday': 'chinese',
               }),
        ],
    },
]


APP_SETTINGS = [
    {'key': 'constant_slots',
     'value': ['white_rice', 'papad', 'pickle', 'chutney']},
    {'key': 'core_min_one_slots',
     'value': ['bread', 'rice', 'starter', 'veg_dry', 'welcome_drink',
               'curd_side', 'nonveg_main', 'veg_gravy']},
    {'key': 'fallback_menu_category', 'value': 'menu_cat_3'},
]
