SUPABASE_URL = "https://lgcoldbfbjduvgwjpjdz.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxnY29sZGJmYmpkdXZnd2pwamR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ4NjM5NzIsImV4cCI6MjA5MDQzOTk3Mn0.v7gNWWLPJ4a45fJXQT9j5vdMK6yan-lWARLFbIT9pMk"
